version: '3.4'

services:
    portfolio:
        image: html-portfolio-image
        build:
            context: .
            dockerfile: src/Dockerfile
    nginx:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        restart: always
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro